### ISSUE TITLE
Difference between catkin build and catkin_make

### ISSUE THREAD

**Issue by nicolasgil95** [fegonzalez7/rob_unal_clase2#7]
Hi,

Following this week guide it says that we have to run the command catkin_make so the previous build updates. When I try to run that command shows the following error:

The build space at _catkin_ws folder_ was previously built by 'catkin build'. Please remove the build space or pick a different build space.

Should I clean the previous build and use the make command or  there's no issue building again the packages?

Thanks

**Comment by fegonzalez7** [comment]
Fancy... english...

If you use catkin build, you must stay with it. 

What I say in the repo is if you have not installed catkin tools, you must use catkin_make.

If you want to swap between compilers, go to your root ws dir and run  catkin clean.
